// <auto-generated />
using GPReptile.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GPReptile.Migrations
{
    [DbContext(typeof(GPContext))]
    [Migration("20200527073646_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GPReptile.Models.DayTransact", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("chg")
                        .HasColumnType("float");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("high")
                        .HasColumnType("float");

                    b.Property<double>("lclose")
                        .HasColumnType("float");

                    b.Property<double>("low")
                        .HasColumnType("float");

                    b.Property<double>("mcap")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("pchg")
                        .HasColumnType("float");

                    b.Property<double>("tcap")
                        .HasColumnType("float");

                    b.Property<double>("tclose")
                        .HasColumnType("float");

                    b.Property<double>("topen")
                        .HasColumnType("float");

                    b.Property<double>("turnover")
                        .HasColumnType("float");

                    b.Property<double>("vaturnover")
                        .HasColumnType("float");

                    b.Property<long>("voturnover")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("DayTransact");
                });
#pragma warning restore 612, 618
        }
    }
}
